{% set name = "aiida-fleur" %}
{% set version = "2.0.0" %}
{% set build = 0 %}
{% set name_code = name + ".code" %}

package:
  name: {{ name }}.meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-fleur-{{ version }}.tar.gz
  sha256: 7ca3e4f3e68254e11e27c77d519a2443781b533dd751d0a5bc39775c739cf6e2

build:
  number: {{ build }}
  noarch: python

requirements:
  run:
    - {{ pin_subpackage(name, exact=True) }}
    - {{ pin_subpackage(name_code, exact=True) }}

outputs:
  - name: {{ name }}
    build:
      noarch: python
      entry_points:
        - aiida-fleur = aiida_fleur.cmdline:cmd_root
      script: 'python -m pip install . --no-deps --ignore-installed -vvv '
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - aiida-core.atomic_tools >=2.0.1,<3
        - future
        - lxml >=4.8,<5
        - markupsafe <2.1.0
        - masci-tools >=0.13,<1
        - more-itertools
        - numpy >=1.16.4,<2
        - pyhull
        - python >=3.8
        - sympy
      run_constrained:
        - {{ name_code }} =={{ version }}
    test:
      imports:
        - aiida_fleur
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name_code }}
    build:
      noarch: python
    requirements:
      run:
        - fleur >=1,<7
    test:
      commands:
        - which fleur_MPI

about:
  home: https://github.com/JuDFTteam/aiida-fleur
  summary: Python FLEUR simulation package containing an AiiDA Plugin for running the FLEUR-code and its input generator. Plus some workflows and utility
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
    - janssenhenning
